### ISSUE TITLE
Trying to assign value of type 'Nil' to a variable of type 'Dictionary'.

### ISSUE THREAD

**Issue by reoreo-zyt** [SakuyaCN/Godot_TeamGame#1]
加载json文件时报错

环境：

<img width="377" alt="image" src="https://user-images.githubusercontent.com/57691895/206892101-390c97a5-f592-461d-ba96-0511a890a165.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/57691895/206892049-3ef60cba-bb91-4198-bf3f-07c0ecc1439d.png">

**Comment by DSPerson** [comment]
me too

**Comment by SakuyaCN** [comment]
如果首次运行报错，拉到文件列表最底下运行场景mod_scene 点击加密即可
